version: '3'

services:
  postgres:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      PGDATA: '/var/lib/postgresql/data/pgdata'
      POSTGRES_DB: 'my_django_app'
      POSTGRES_USER: 'my_django_app'
      POSTGRES_PASSWORD: 'mysecretpassword'
    volumes: 
      - django-data:/var/lib/postgresql/data/pgdata

  django:
    image: docker-django
    build: .
    working_dir: /app
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - django_env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres

volumes:
  django-data:
